-- 0076c_acervo_stack_seed.sql — EXEMPLO da forma de uma linha de acervo.stack.
--
-- Ate o card #3010 este arquivo era o seed dos 11 stacks DESTA maquina, gerado de
-- stacks.json por gerar_seed_stack.py (#2703), com compose, rotas e segredos apontando a
-- pasta de trabalho da conta. Caminho de host nao mora em seed do produto (desenho do
-- #3010 §4): as 11 linhas reais sao gravadas e corrigidas por
-- 0091_acervo_stack_release_instancia.sql e, dali em diante, por `acervo stack def|import`
-- (nunca UPDATE a mao). O numero fica para a ordem das migracoes aplicadas nao mudar.
--
-- Nada aqui grava linha: o insert abaixo e comentario, para ler e copiar.
--
-- Forma (serializacao de bin/_acervo/stack: rotas/gate/segredos/reversao/profiles via
-- json.dumps::jsonb; compose com mais de um arquivo como lista JSON, na ordem do -f):
--
--   insert into acervo.stack (slug,papel,critico,repo,compose,rotas,segredos,reversao,gate,profiles,nota) values
--     ('<stack>',
--      '<papel da unidade de deploy>',
--      false,
--      'platafirma-<familia>',
--      '["/opt/platafirma/current/<curto>/<caminho-do-compose>", "/srv/platafirma/casa/deploy/<stack>/compose.override.yaml"]',
--      null,                                                   -- ou '"<ingress>"'::jsonb
--      '["/srv/platafirma/casa/segredos/<stack>/"]'::jsonb,    -- '[]' declara que nao exige
--      '{"via": "promover", "quem": "<cadeira>", "janela_min": 1, "estado": "<o que nao volta>", "nota": "<como se desfaz>", "provado_em": null}'::jsonb,
--      null,                                                   -- ou '"<compose do gate>"'::jsonb
--      null,                                                   -- ou '["<profile>"]'::jsonb
--      '<nota>')
--   on conflict (slug) do update set
--     papel = excluded.papel, critico = excluded.critico, repo = excluded.repo,
--     compose = excluded.compose, rotas = excluded.rotas, segredos = excluded.segredos,
--     reversao = excluded.reversao, gate = excluded.gate, profiles = excluded.profiles,
--     nota = excluded.nota;
--
-- As ligacoes medidas instancia -> stack (keycloak->core, matrix->chat, rastreador->2
-- stacks), que este seed gravava, tambem passaram a 0091.

begin;
commit;
