-- 0076c_acervo_stack_seed.sql — seed dos 11 stacks. GERADO de stacks.json
-- por gerar_seed_stack.py (#2703). Serializacao JSON FIEL: rotas/gate/segredos/
-- reversao/profiles via json.dumps::jsonb; compose-lista como JSON, nao repr.
-- Idempotente: on conflict (slug) do UPDATE (nao 'do nothing' — o ponto e
-- corrigir linha ja existente com serializacao errada).
begin;

insert into acervo.stack (slug,papel,critico,repo,compose,rotas,segredos,reversao,gate,profiles,nota) values
  ('core','control-plane: IAM, borda, politica de seguranca',true,'platafirma-core','~/AI/deploy/core/docker-compose.yml','"deploy/cloudflared-config.yml"'::jsonb,'[".env", "secrets/cloudflared/01452d04-7dd9-40ea-be5a-f8bcaa7bed8f.json", "~/.config/ops/env"]'::jsonb,'{"via": "promover", "quem": "claudinho-TI", "janela_min": 1, "estado": "identidade-db, keycloak-db e mdm-rh-db em volume: NAO voltam com o codigo. Migracao de realm feita para frente e irreversivel por aqui.", "nota": "Critica: derruba a borda e o IAM junto. Reverter e recriar, nao ''down''. Sessao aberta de todo mundo cai.", "provado_em": "2026-08-21 — ida e volta pelo verbo (59bbdd6 -> f674555 -> 59bbdd6), 21s e 29s, keycloak, identidade-db, mdm-rh-db e landing recriados; cloudflared e o tunel voltaram sozinhos."}'::jsonb,null,null,null),
  ('motor','motor: malha de mensageria (msg)',true,'platafirma-motor','~/AI/deploy/motor/docker-compose.yml',null,'[".env"]'::jsonb,'{"via": "promover", "quem": "claudinho-TI", "janela_min": 1, "estado": "motor-pg em volume; motor-msg-mem e cache allkeys-lru e pode ser perdido sem dano.", "nota": "Critica: msg para enquanto recria. Consumidor com stream aberto reconecta sozinho.", "provado_em": "2026-08-21 — ida e volta pelo verbo (b92c528 -> b0225d8 -> b92c528), 8s cada, os quatro conteineres recriados. msg parou e voltou dentro da janela."}'::jsonb,null,null,null),
  ('rag','recuperacao: extrator, indice e API do acervo',false,'platafirma-conhecimento','["~/AI/deploy/conhecimento/rag/docker-compose.yml", "~/AI/deploy/conhecimento/rag/docker-compose.gpu.yml"]',null,'[".env"]'::jsonb,'{"via": "promover", "quem": "claudinho-TI", "janela_min": 1, "estado": "indice vetorial em volume: nao volta com o codigo, e reindexar custa horas de GPU.", "nota": "Overlay de GPU e perfil `serving` entram na volta; sem --profile o rag-api fica fora e o verbo nao acusa.", "provado_em": "2026-08-21 — ida e volta pelo verbo (f84def9 -> bda62dd -> f84def9), 26s e 25s, minio/pg/api recriados. Acervo conferido DEPOIS: 1639 arquivos e 4.150.556.269 bytes, identico ao de antes. Backup completo em ~/AI/backups/minio-obras-20260821T071055 (md5 de amostra confere) existia antes do ensaio."}'::jsonb,null,'["serving"]'::jsonb,null),
  ('acervo-api','API do acervo',false,'platafirma-conhecimento','~/AI/platafirma-conhecimento/acervo-api/docker-compose.yml',null,'[".env"]'::jsonb,'{"via": "up", "quem": "claudinho-TI", "janela_min": 1, "estado": "le o Postgres do acervo, que nao e desta stack: nada a perder aqui.", "nota": "Aponta clone de trabalho: `promover` recusa. A volta e checkout no clone + `deploy acervo-api up -d --build`. Ensaio de 21/08 usou `git checkout <ref> -- acervo-api/`, nao troca de branch: o clone e compartilhado e trocar branch quebraria quem edita.", "provado_em": "2026-08-21 — ida e volta executada e MEDIDA: acervo-api/ voltado a 5f9a26a, rebuild, container Recreated e /health 200 em 4s; volta a f84def9, Recreated, /health 200 em 3s. Janela real ~7s, nao os ~5 min estimados. Clone limpo depois."}'::jsonb,null,null,null),
  ('conhecimento','wiki e MCP de conhecimento',true,'platafirma-conhecimento','["~/AI/deploy/conhecimento/docker-compose.yml", "~/AI/deploy/conhecimento/docker-compose.override.yml"]',null,'[".env"]'::jsonb,'{"via": "promover", "quem": "claudinho-TI", "janela_min": 1, "estado": "dbdata (MariaDB da wiki) e images em volume: conteudo NAO volta com o codigo. Edicao feita depois do commit ruim permanece, e e isso que se quer.", "nota": "Critica. O override do LocalSettings.php e bind de arquivo unico: promover troca o inode e e por isso que a volta tambem tem de ser `promover`, nunca `restart`.", "provado_em": "2026-08-21 — ida e volta pelo verbo (f84def9 -> bda62dd -> f84def9), 25s cada, wiki-db e mediawiki recriados, /health do wiki-mcp 200 no fim. dbdata intacto."}'::jsonb,null,null,null),
  ('harness-controle','plano de controle do harness: agregador e tela',false,'platafirma-harness','~/AI/deploy/harness/controle/compose.yaml',null,'[]'::jsonb,'{"via": "promover", "quem": "claudinho-TI", "janela_min": 5, "estado": "sem volume: a volta e integral.", "nota": "O AGREGADOR e unit systemd --user, fora deste compose: reverter a tela nao reverte o agregador.", "provado_em": "2026-08-21 — ida e volta executada pelo verbo (6fd9997 -> 9825a5a -> 6fd9997), conteiner recriado nos tres passos"}'::jsonb,null,null,'reparticao por direcao: a TELA e conteiner, servida por este compose (front vem da imagem, arq:0056); o AGREGADOR e unit systemd --user em controle/systemd/ no repo, porque os verbos do host nao sobrevivem a containerizacao.'),
  ('jaiminho','corpo do colaborador externo Jaiminho: fala com a API do Google e com o ops-server pelo client proprio no realm',false,'platafirma-harness','~/AI/platafirma-harness/jaiminho/docker-compose.yml',null,'[".env"]'::jsonb,'{"via": "up", "quem": "claudinho-TI", "janela_min": 2, "estado": "volume `casa` guarda o login do agy: recriar sem cuidado desloga o braco.", "nota": "Aponta clone de trabalho: `promover` recusa. Volta = checkout no clone + `deploy jaiminho up -d --build jaiminho-server`. Ver residuo do #2286 (mesa #221): quem serve a 8023 e o daemon uid 1001.", "provado_em": "2026-08-21 — ida e volta por checkout de caminho (jaiminho/ em 57de907 e de volta a c1bd0b5), 63s e 64s, jaiminho-server recriado e /health 200 na 8023. Volume `casa` intacto: o braco nao deslogou."}'::jsonb,null,null,'rede bridge propria, sem alcance ao loopback do host — o Valkey da malha e inalcancavel de dentro (medido em 14/08/2026). Sem rota no tunel: nao e superficie publica.'),
  ('chat','superficie de conversa: homeserver Matrix, banco proprio e Application Service',false,'platafirma-harness','~/AI/platafirma-harness/chat/docker-compose.yml','"~/AI/deploy/core/deploy/cloudflared-config.yml"'::jsonb,'[".env", "~/AI/var/secrets/matrix/oidc-client-secret", "~/AI/var/secrets/matrix/signing.key", "~/AI/var/secrets/matrix/segredos.yaml", "~/AI/var/secrets/matrix/registration.yaml"]'::jsonb,'{"via": "up", "quem": "claudinho-TI", "janela_min": 1, "estado": "banco do Synapse em volume: mensagem nao volta, e nem deve.", "nota": "Aponta clone de trabalho: `promover` recusa. signing.key fora do git — perde-la invalida o homeserver, e nenhuma volta de codigo a recupera.", "provado_em": "2026-08-21 — ida e volta por checkout de caminho (chat/ em 1f985b5 e de volta a c1bd0b5), 18s cada, chat-recepcao recriado. chat-pg e chat-synapse NAO foram recriados: o commit so tocava a recepcao, e reversao parcial e o caso real."}'::jsonb,null,null,'O Synapse fica em duas redes: `interna` (internal, com banco e AS — e por ela que a Admin API responde, e so por ela) e a do conhecimento, que e onde o cloudflared vive. Em rootless o container nao alcanca o loopback do host, entao estar na rede do cloudflared e a unica forma de a borda chegar no homeserver. O ingress mora no core, e por isso `rotas` aponta para fora deste repo.'),
  ('rastreador','rastreador de trabalho: API e banco proprio do boneco',false,'platafirma-rastreador','~/AI/deploy/rastreador/docker-compose.yml','"~/AI/deploy/core/deploy/cloudflared-config.yml"'::jsonb,'[".env"]'::jsonb,'{"via": "promover", "quem": "claudinho-TI", "janela_min": 1, "estado": "rastreador-db em volume: card criado depois do commit ruim SOBREVIVE a volta. Migracao de schema aplicada nao desfaz sozinha.", "nota": "Superficie publica: a volta que muda contrato de API quebra a tela, que e de claudinha-produto. Avisar antes.", "provado_em": "2026-08-21 — ida e volta pelo proprio verbo (0a14392 -> 2d8e414 -> 0a14392): rastreador-db e rastreador-api Recreated nos dois passos, /health 200 em 10s cada, e o card #184 lido antes e depois byte a byte igual (o volume nao se mexeu). Janela real ~20s."}'::jsonb,'"~/AI/deploy/core/docker-compose.yml"'::jsonb,null,'Boneco do card #465, API-only por arq:0056 — o comentario 335 recortou a tela, que volta no #468. Aponta para o CLONE DE TRABALHO, nao para um worktree de deploy: ~/AI/deploy/rastreador nao existe, entao `promover` recusa e `conferir servico` marca DERIVA. E o mesmo padrao de acervo-api, chat e jaiminho. DESDE O #469 a stack tem superficie publica: tarefas.platafirma.org entra no `oauth2-proxy-rastreador`, que vive na stack CORE e alcanca esta API pela rede `pf-borda-rastreador`. Por isso `rotas` e `gate` apontam os dois para fora deste repo — mesma razao do `chat`, cujo ingress tambem mora no core. Reverter continua sendo `deploy rastreador down` mais apagar o volume.'),
  ('rastreador-tela','superficie de tela do rastreador: a tela servida por si, sem o back',false,'platafirma-ui','~/AI/deploy/rastreador-tela/app/rastreador/docker-compose.yml','"~/AI/deploy/core/deploy/cloudflared-config.yml"'::jsonb,'[]'::jsonb,'{"via": "promover", "quem": "claudinha-produto", "janela_min": 5, "estado": "sem volume e sem segredo: a volta e integral.", "nota": "Deploy desta stack e de claudinha-produto desde o #197. claudinho-TI reverte so em incidente, e avisa. NAO ensaiada em 21/08 por fronteira de cadeira: deploy desta stack e de claudinha-produto. FORA DO ESCOPO do #184 por ordem do dono em 21/08/2026: o card cobre as stacks de claudinho-TI, e o deploy desta e de claudinha-produto. Ensaio, quando houver, e dela.", "provado_em": "FORA DE ESCOPO por ordem do dono, 21/08/2026 — o deploy desta stack e de claudinha-produto desde o #197, e ensaio de reversao acompanha o dono do deploy. A declaracao (via, janela, quem, o que nao volta) segue valendo e nao precisa de ensaio meu."}'::jsonb,'"~/AI/deploy/core/docker-compose.yml"'::jsonb,null,'Segunda saida de release da platafirma-ui (arq:0057 emendando arq:0042): a biblioteca sai como imagem versionada, cada superficie de tela sai como SERVICO proprio. Alcancada pelo `oauth2-proxy-rastreador`, que vive na stack CORE, pela rede `pf-borda-rastreador` — por isso `rotas` e `gate` apontam para fora deste repo, mesma razao do `rastreador` e do `chat`. `segredos: []` DECLARA que a stack nao exige nenhum, e e aceite do #187, nao omissao: front que monta segredo de outra camada e o que o instrumento passa a reprovar. Deploy desta stack e de claudinha-produto a partir do fechamento do #187 (card #197).'),
  ('harness-sessao','substrato das entidades operacionais de sessao: fita, giro, pacote, peca servida, mesa',false,'platafirma-harness','~/AI/platafirma-harness/sessao/compose.yaml',null,'["sessao/.env"]'::jsonb,'{"via": "up", "quem": "claudinho-TI", "janela_min": 5, "estado": "sessao-db em volume: fita, giro e mesa NAO voltam com o codigo. DDL em sessao/init/ so roda em volume novo.", "nota": "Aponta clone de trabalho: `promover` recusa. Volta de DDL ja aplicada exige migracao para frente, nunca `down -v`. ENSAIO TENTADO E RECUSADO em 21/08: sessao-db e imagem postgres pura, sem build — `up -d --build` nao recria nada quando o conteudo nao muda, e o ensaio passaria verde sem ter revertido (prova falsa). Ensaio valido exige --force-recreate, que derruba o banco da fita em curso; fica para janela sem sessao viva.", "provado_em": null}'::jsonb,null,null,'Aponta para o CLONE DE TRABALHO, como chat e jaiminho: nao ha worktree ~/AI/deploy/harness/sessao, entao `promover` recusa e `conferir servico` marca DERIVA. Instancia propria, e nao servico do `harness-controle`, porque ali o ciclo de vida e o da TELA — `deploy harness-controle down` levaria a memoria de trabalho junto. Fase 6 do card #189; DDL em sessao/init/, versionada.')
on conflict (slug) do update set
  papel = excluded.papel,
  critico = excluded.critico,
  repo = excluded.repo,
  compose = excluded.compose,
  rotas = excluded.rotas,
  segredos = excluded.segredos,
  reversao = excluded.reversao,
  gate = excluded.gate,
  profiles = excluded.profiles,
  nota = excluded.nota;


-- ligacoes MEDIDAS (nao serializadas: sem bug): keycloak->core; matrix->chat;
-- rastreador->2 stacks. Preservado do seed anterior.
insert into acervo.instancia_roda_em_stack (instancia_id,stack_id)
  select i.id,s.id from acervo.ferramental_instancia i, acervo.stack s where i.slug='keycloak' and s.slug='core'
union all
  select i.id,s.id from acervo.ferramental_instancia i, acervo.stack s where i.slug='matrix' and s.slug='chat'
union all
  select i.id,s.id from acervo.ferramental_instancia i, acervo.stack s where i.slug='rastreador' and s.slug='rastreador'
union all
  select i.id,s.id from acervo.ferramental_instancia i, acervo.stack s where i.slug='rastreador' and s.slug='rastreador-tela'
on conflict do nothing;

commit;
