-- 0091_acervo_stack_release_instancia.sql — acervo.stack sem a pasta de trabalho da conta.
-- Card #3010 (producao sem bancada), desenho §4. NAO se aplica sozinha: entra por
-- `migrar aplicar rag` na fase de host, depois do bootstrap de /srv/platafirma/casa e da
-- primeira promocao das familias para /opt/platafirma.
--
-- O que corrige, linha a linha, nas 11 stacks que o seed 0076c gravou:
--   compose  base na RELEASE, no caminho que ja tem no repo:
--              /opt/platafirma/current/<curto>/<caminho-do-compose>
--            + sobreposicao da INSTANCIA:
--              /srv/platafirma/casa/deploy/<stack>/compose.override.yaml
--            (lista, na ordem do -f; o `deploy` sobe com o nome de projeto de sempre).
--   rotas    o ingress do tunel e config da instancia: /srv/platafirma/casa/deploy/core/cloudflared.yml
--   gate     o compose do core na release.
--   segredos um diretorio por stack em /srv/platafirma/casa/segredos/<stack>/ (um arquivo
--            por variavel; o `deploy` materializa o --env-file em tmpfs), o cofre matrix em
--            segredos/matrix/, a credencial do tunel em segredos/core/cloudflared/.
--   reversao stacks que apontavam o clone de trabalho passam a `promover` pela release.
--
-- Upsert COMPLETO e nao UPDATE de coluna: em banco novo, o seed 0076c virou exemplo e nao
-- grava stack nenhuma — esta migracao e quem as cria. Em banco existente, corrige.
-- Idempotente: on conflict (slug) do update. Gerada do 0076c com a serializacao de
-- bin/_acervo/stack (json.dumps::jsonb; compose-lista como JSON, nao repr).
begin;

insert into acervo.stack (slug,papel,critico,repo,compose,rotas,segredos,reversao,gate,profiles,nota) values
  ('core','control-plane: IAM, borda, politica de seguranca',true,'platafirma-core','["/opt/platafirma/current/core/docker-compose.yml", "/srv/platafirma/casa/deploy/core/compose.override.yaml"]','"/srv/platafirma/casa/deploy/core/cloudflared.yml"'::jsonb,'["/srv/platafirma/casa/segredos/core/", "/srv/platafirma/casa/segredos/core/cloudflared/01452d04-7dd9-40ea-be5a-f8bcaa7bed8f.json", "~/.config/ops/env"]'::jsonb,'{"via": "promover", "quem": "claudinho-TI", "janela_min": 1, "estado": "identidade-db, keycloak-db e mdm-rh-db em volume: NAO voltam com o codigo. Migracao de realm feita para frente e irreversivel por aqui.", "nota": "Critica: derruba a borda e o IAM junto. Reverter e recriar, nao ''down''. Sessao aberta de todo mundo cai.", "provado_em": "2026-08-21 — ida e volta pelo verbo (59bbdd6 -> f674555 -> 59bbdd6), 21s e 29s, keycloak, identidade-db, mdm-rh-db e landing recriados; cloudflared e o tunel voltaram sozinhos."}'::jsonb,null,null,null),
  ('motor','motor: malha de mensageria (msg)',true,'platafirma-motor','["/opt/platafirma/current/motor/docker-compose.yml", "/srv/platafirma/casa/deploy/motor/compose.override.yaml"]',null,'["/srv/platafirma/casa/segredos/motor/"]'::jsonb,'{"via": "promover", "quem": "claudinho-TI", "janela_min": 1, "estado": "motor-pg em volume; motor-msg-mem e cache allkeys-lru e pode ser perdido sem dano.", "nota": "Critica: msg para enquanto recria. Consumidor com stream aberto reconecta sozinho.", "provado_em": "2026-08-21 — ida e volta pelo verbo (b92c528 -> b0225d8 -> b92c528), 8s cada, os quatro conteineres recriados. msg parou e voltou dentro da janela."}'::jsonb,null,null,null),
  ('rag','recuperacao: extrator, indice e API do acervo',false,'platafirma-conhecimento','["/opt/platafirma/current/conhecimento/rag/docker-compose.yml", "/opt/platafirma/current/conhecimento/rag/docker-compose.gpu.yml", "/srv/platafirma/casa/deploy/rag/compose.override.yaml"]',null,'["/srv/platafirma/casa/segredos/rag/"]'::jsonb,'{"via": "promover", "quem": "claudinho-TI", "janela_min": 1, "estado": "indice vetorial em volume: nao volta com o codigo, e reindexar custa horas de GPU.", "nota": "Overlay de GPU e perfil `serving` entram na volta; sem --profile o rag-api fica fora e o verbo nao acusa.", "provado_em": "2026-08-21 — ida e volta pelo verbo (f84def9 -> bda62dd -> f84def9), 26s e 25s, minio/pg/api recriados. Acervo conferido DEPOIS: 1639 arquivos e 4.150.556.269 bytes, identico ao de antes. Backup completo na pasta de trabalho da conta (backups/minio-obras-20260821T071055, estado de 21/08/2026) (md5 de amostra confere) existia antes do ensaio."}'::jsonb,null,'["serving"]'::jsonb,null),
  ('acervo-api','API do acervo',false,'platafirma-conhecimento','["/opt/platafirma/current/conhecimento/acervo-api/docker-compose.yml", "/srv/platafirma/casa/deploy/acervo-api/compose.override.yaml"]',null,'["/srv/platafirma/casa/segredos/acervo-api/"]'::jsonb,'{"via": "promover", "quem": "claudinho-TI", "janela_min": 1, "estado": "le o Postgres do acervo, que nao e desta stack: nada a perder aqui.", "nota": "Base na release (/opt/platafirma/current/conhecimento), sobreposicao em /srv/platafirma/casa/deploy/acervo-api/: a volta e `release promover platafirma-conhecimento <rev anterior>` seguida de `deploy acervo-api promover`. Ate 15/09/2026 apontava o clone de trabalho; o ensaio de 21/08 usou `git checkout <ref> -- acervo-api/` nele, sem trocar branch.", "provado_em": "2026-08-21 — ida e volta executada e MEDIDA: acervo-api/ voltado a 5f9a26a, rebuild, container Recreated e /health 200 em 4s; volta a f84def9, Recreated, /health 200 em 3s. Janela real ~7s, nao os ~5 min estimados. Clone limpo depois."}'::jsonb,null,null,null),
  ('conhecimento','wiki e MCP de conhecimento',true,'platafirma-conhecimento','["/opt/platafirma/current/conhecimento/docker-compose.yml", "/opt/platafirma/current/conhecimento/docker-compose.override.yml", "/srv/platafirma/casa/deploy/conhecimento/compose.override.yaml"]',null,'["/srv/platafirma/casa/segredos/conhecimento/"]'::jsonb,'{"via": "promover", "quem": "claudinho-TI", "janela_min": 1, "estado": "dbdata (MariaDB da wiki) e images em volume: conteudo NAO volta com o codigo. Edicao feita depois do commit ruim permanece, e e isso que se quer.", "nota": "Critica. O override do LocalSettings.php e bind de arquivo unico: promover troca o inode e e por isso que a volta tambem tem de ser `promover`, nunca `restart`.", "provado_em": "2026-08-21 — ida e volta pelo verbo (f84def9 -> bda62dd -> f84def9), 25s cada, wiki-db e mediawiki recriados, /health do wiki-mcp 200 no fim. dbdata intacto."}'::jsonb,null,null,null),
  ('harness-controle','plano de controle do harness: agregador e tela',false,'platafirma-harness','["/opt/platafirma/current/harness/controle/compose.yaml", "/srv/platafirma/casa/deploy/harness-controle/compose.override.yaml"]',null,'[]'::jsonb,'{"via": "promover", "quem": "claudinho-TI", "janela_min": 5, "estado": "sem volume: a volta e integral.", "nota": "O AGREGADOR e unit systemd --user, fora deste compose: reverter a tela nao reverte o agregador.", "provado_em": "2026-08-21 — ida e volta executada pelo verbo (6fd9997 -> 9825a5a -> 6fd9997), conteiner recriado nos tres passos"}'::jsonb,null,null,'reparticao por direcao: a TELA e conteiner, servida por este compose (front vem da imagem, arq:0056); o AGREGADOR e unit systemd --user em controle/systemd/ no repo, porque os verbos do host nao sobrevivem a containerizacao.'),
  ('jaiminho','corpo do colaborador externo Jaiminho: fala com a API do Google e com o ops-server pelo client proprio no realm',false,'platafirma-harness','["/opt/platafirma/current/harness/jaiminho/docker-compose.yml", "/srv/platafirma/casa/deploy/jaiminho/compose.override.yaml"]',null,'["/srv/platafirma/casa/segredos/jaiminho/"]'::jsonb,'{"via": "promover", "quem": "claudinho-TI", "janela_min": 2, "estado": "volume `casa` guarda o login do agy: recriar sem cuidado desloga o braco.", "nota": "Base na release (/opt/platafirma/current/harness), sobreposicao em /srv/platafirma/casa/deploy/jaiminho/: a volta e `release promover platafirma-harness <rev anterior>` seguida de `deploy jaiminho promover`. Ate 15/09/2026 apontava o clone de trabalho. Ver residuo do #2286 (mesa #221): quem serve a 8023 e o daemon uid 1001.", "provado_em": "2026-08-21 — ida e volta por checkout de caminho (jaiminho/ em 57de907 e de volta a c1bd0b5), 63s e 64s, jaiminho-server recriado e /health 200 na 8023. Volume `casa` intacto: o braco nao deslogou."}'::jsonb,null,null,'rede bridge propria, sem alcance ao loopback do host — o Valkey da malha e inalcancavel de dentro (medido em 14/08/2026). Sem rota no tunel: nao e superficie publica.'),
  ('chat','superficie de conversa: homeserver Matrix, banco proprio e Application Service',false,'platafirma-harness','["/opt/platafirma/current/harness/chat/docker-compose.yml", "/srv/platafirma/casa/deploy/chat/compose.override.yaml"]','"/srv/platafirma/casa/deploy/core/cloudflared.yml"'::jsonb,'["/srv/platafirma/casa/segredos/chat/", "/srv/platafirma/casa/segredos/matrix/oidc-client-secret", "/srv/platafirma/casa/segredos/matrix/signing.key", "/srv/platafirma/casa/segredos/matrix/segredos.yaml", "/srv/platafirma/casa/segredos/matrix/registration.yaml"]'::jsonb,'{"via": "promover", "quem": "claudinho-TI", "janela_min": 1, "estado": "banco do Synapse em volume: mensagem nao volta, e nem deve.", "nota": "Base na release (/opt/platafirma/current/harness), sobreposicao em /srv/platafirma/casa/deploy/chat/: a volta e `release promover platafirma-harness <rev anterior>` seguida de `deploy chat promover`. Ate 15/09/2026 apontava o clone de trabalho. signing.key fora do git — perde-la invalida o homeserver, e nenhuma volta de codigo a recupera.", "provado_em": "2026-08-21 — ida e volta por checkout de caminho (chat/ em 1f985b5 e de volta a c1bd0b5), 18s cada, chat-recepcao recriado. chat-pg e chat-synapse NAO foram recriados: o commit so tocava a recepcao, e reversao parcial e o caso real."}'::jsonb,null,null,'O Synapse fica em duas redes: `interna` (internal, com banco e AS — e por ela que a Admin API responde, e so por ela) e a do conhecimento, que e onde o cloudflared vive. Em rootless o container nao alcanca o loopback do host, entao estar na rede do cloudflared e a unica forma de a borda chegar no homeserver. O ingress mora no core, e por isso `rotas` aponta para fora deste repo.'),
  ('rastreador','rastreador de trabalho: API e banco proprio do boneco',false,'platafirma-rastreador','["/opt/platafirma/current/rastreador/docker-compose.yml", "/srv/platafirma/casa/deploy/rastreador/compose.override.yaml"]','"/srv/platafirma/casa/deploy/core/cloudflared.yml"'::jsonb,'["/srv/platafirma/casa/segredos/rastreador/"]'::jsonb,'{"via": "promover", "quem": "claudinho-TI", "janela_min": 1, "estado": "rastreador-db em volume: card criado depois do commit ruim SOBREVIVE a volta. Migracao de schema aplicada nao desfaz sozinha.", "nota": "Superficie publica: a volta que muda contrato de API quebra a tela, que e de claudinha-produto. Avisar antes.", "provado_em": "2026-08-21 — ida e volta pelo proprio verbo (0a14392 -> 2d8e414 -> 0a14392): rastreador-db e rastreador-api Recreated nos dois passos, /health 200 em 10s cada, e o card #184 lido antes e depois byte a byte igual (o volume nao se mexeu). Janela real ~20s."}'::jsonb,'"/opt/platafirma/current/core/docker-compose.yml"'::jsonb,null,'Boneco do card #465, API-only por arq:0056 — o comentario 335 recortou a tela, que volta no #468. Desde o card #3010 a base sobe da release e a sobreposicao da instancia (ate 15/09/2026 apontava o clone de trabalho, como acervo-api, chat e jaiminho). DESDE O #469 a stack tem superficie publica: tarefas.platafirma.org entra no `oauth2-proxy-rastreador`, que vive na stack CORE e alcanca esta API pela rede `pf-borda-rastreador`. Por isso `rotas` e `gate` apontam os dois para fora deste repo — mesma razao do `chat`, cujo ingress tambem mora no core. Reverter continua sendo `deploy rastreador down` mais apagar o volume.'),
  ('rastreador-tela','superficie de tela do rastreador: a tela servida por si, sem o back',false,'platafirma-ui','["/opt/platafirma/current/ui/app/rastreador/docker-compose.yml", "/srv/platafirma/casa/deploy/rastreador-tela/compose.override.yaml"]','"/srv/platafirma/casa/deploy/core/cloudflared.yml"'::jsonb,'[]'::jsonb,'{"via": "promover", "quem": "claudinha-produto", "janela_min": 5, "estado": "sem volume e sem segredo: a volta e integral.", "nota": "Deploy desta stack e de claudinha-produto desde o #197. claudinho-TI reverte so em incidente, e avisa. NAO ensaiada em 21/08 por fronteira de cadeira: deploy desta stack e de claudinha-produto. FORA DO ESCOPO do #184 por ordem do dono em 21/08/2026: o card cobre as stacks de claudinho-TI, e o deploy desta e de claudinha-produto. Ensaio, quando houver, e dela.", "provado_em": "FORA DE ESCOPO por ordem do dono, 21/08/2026 — o deploy desta stack e de claudinha-produto desde o #197, e ensaio de reversao acompanha o dono do deploy. A declaracao (via, janela, quem, o que nao volta) segue valendo e nao precisa de ensaio meu."}'::jsonb,'"/opt/platafirma/current/core/docker-compose.yml"'::jsonb,null,'Segunda saida de release da platafirma-ui (arq:0057 emendando arq:0042): a biblioteca sai como imagem versionada, cada superficie de tela sai como SERVICO proprio. Alcancada pelo `oauth2-proxy-rastreador`, que vive na stack CORE, pela rede `pf-borda-rastreador` — por isso `rotas` e `gate` apontam para fora deste repo, mesma razao do `rastreador` e do `chat`. `segredos: []` DECLARA que a stack nao exige nenhum, e e aceite do #187, nao omissao: front que monta segredo de outra camada e o que o instrumento passa a reprovar. Deploy desta stack e de claudinha-produto a partir do fechamento do #187 (card #197).'),
  ('harness-sessao','substrato das entidades operacionais de sessao: fita, giro, pacote, peca servida, mesa',false,'platafirma-harness','["/opt/platafirma/current/harness/sessao/compose.yaml", "/srv/platafirma/casa/deploy/harness-sessao/compose.override.yaml"]',null,'["/srv/platafirma/casa/segredos/harness-sessao/"]'::jsonb,'{"via": "promover", "quem": "claudinho-TI", "janela_min": 5, "estado": "sessao-db em volume: fita, giro e mesa NAO voltam com o codigo. DDL em sessao/init/ so roda em volume novo.", "nota": "Base na release (/opt/platafirma/current/harness), sobreposicao em /srv/platafirma/casa/deploy/harness-sessao/: a volta e `release promover platafirma-harness <rev anterior>` seguida de `deploy harness-sessao promover`. Ate 15/09/2026 apontava o clone de trabalho. Volta de DDL ja aplicada exige migracao para frente, nunca `down -v`. ENSAIO TENTADO E RECUSADO em 21/08: sessao-db e imagem postgres pura, sem build — `up -d --build` nao recria nada quando o conteudo nao muda, e o ensaio passaria verde sem ter revertido (prova falsa). Ensaio valido exige --force-recreate, que derruba o banco da fita em curso; fica para janela sem sessao viva.", "provado_em": null}'::jsonb,null,null,'Desde o card #3010 a base sobe da release e a sobreposicao da instancia (ate 15/09/2026 apontava o clone de trabalho, como chat e jaiminho). Instancia propria, e nao servico do `harness-controle`, porque ali o ciclo de vida e o da TELA — `deploy harness-controle down` levaria a memoria de trabalho junto. Fase 6 do card #189; DDL em sessao/init/, versionada.')
on conflict (slug) do update set
  papel = excluded.papel,
  critico = excluded.critico,
  repo = excluded.repo,
  compose = excluded.compose,
  rotas = excluded.rotas,
  segredos = excluded.segredos,
  reversao = excluded.reversao,
  gate = excluded.gate,
  profiles = excluded.profiles,
  nota = excluded.nota;

-- ligacoes MEDIDAS (vindas do 0076c, que deixou de grava-las): keycloak->core;
-- matrix->chat; rastreador->2 stacks.
insert into acervo.instancia_roda_em_stack (instancia_id,stack_id)
  select i.id,s.id from acervo.ferramental_instancia i, acervo.stack s where i.slug='keycloak' and s.slug='core'
union all
  select i.id,s.id from acervo.ferramental_instancia i, acervo.stack s where i.slug='matrix' and s.slug='chat'
union all
  select i.id,s.id from acervo.ferramental_instancia i, acervo.stack s where i.slug='rastreador' and s.slug='rastreador'
union all
  select i.id,s.id from acervo.ferramental_instancia i, acervo.stack s where i.slug='rastreador' and s.slug='rastreador-tela'
on conflict do nothing;

-- Aceite embutido: nenhuma linha aponta a pasta de trabalho da conta, nem caminho relativo.
do $$
declare n int;
begin
  select count(*) into n from acervo.stack
   where concat_ws(' ', compose, rotas::text, segredos::text, reversao::text, gate::text, nota)
         ~ ('/' || 'AI([/[:space:]"]|$)');
  if n > 0 then
    raise exception 'acervo.stack: % linha(s) ainda apontam a pasta de trabalho da conta', n;
  end if;
  select count(*) into n from acervo.stack
   where compose !~ '^(\[")?/opt/platafirma/current/';
  if n > 0 then
    raise exception 'acervo.stack: % linha(s) com compose fora da release', n;
  end if;
end $$;

commit;
